<?php

namespace Commandes\CommandesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AchatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class AchatsRepository extends EntityRepository
{
    public function findByProd($produit)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.produits = :produit')


            ->orderBy('u.id','desc')
            ->setParameter('produit', $produit);

        return $qb->getQuery()->getResult();
    }

}
