<?php

namespace Commandes\CommandesBundle\Repository;

/**
 * AcheteursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcheteursRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->orderBy('u.id', 'DESC');

        return $qb->getQuery()->getArrayResult();
    }

    public function findByUser($user)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')

            ->where('u.user = :user')
            ->orderBy('u.id', 'DESC')
            ->setParameter('user', $user)


        ;
        return $qb->getQuery()->getResult();
    }

    public function search($mot,$user)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')

            ->andWhere('u.nom LIKE :value OR u.prenom LIKE :value OR u.nif LIKE :value OR u.nrc LIKE :value OR u.email LIKE :value OR u.telephone LIKE :value OR u.adresse LIKE :value OR u.ville LIKE :value  ')

            ->andWhere('u.user = :user')

            ->setParameter('value', '%'.$mot.'%')
            ->setParameter('user', $user);
        ;
        return $qb->getQuery()->getResult();
    }

}
