<?php

namespace Commandes\CommandesBundle\Repository;

/**
 * AprofactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AprofactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByProd($produit)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.produits = :produit')
            ->andWhere('u.qte >= 1')
            ->orderBy('u.id','desc')
            ->setParameter('produit', $produit);

        return $qb->getQuery()->getResult();
    }
}
