<?php

namespace Commandes\CommandesBundle\Repository;

/**
 * ConfigsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigsRepository extends \Doctrine\ORM\EntityRepository
{
}
