<?php

namespace Commandes\CommandesBundle\Repository;

/**
 * BonscommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepensesRepository extends \Doctrine\ORM\EntityRepository
{
    public function idfact($user)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->orderBy('u.nf', 'DESC')
            ->where('u.user = :user')
            ->setMaxResults(1)
            ->setParameter('user', $user);


        return $qb->getQuery()->getResult();
    }



    public function findByType($type,$user)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.type = :type')
            ->andWhere('u.user = :user')
            ->setParameter('type', $type)
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }
    public function findLast($user) {
        $qb = $this->createQueryBuilder('u')
            ->where('u.user = :user')
            ->setMaxResults(1)
            ->orderBy('u.id', 'DESC')
            ->setParameter('user', $user);
        return $qb->getQuery()->getResult();
    }
    public function search($etat,$type,$du,$au,$zone,$mot,$user)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->innerJoin('u.zonnestocks', 'z')
            ->innerJoin('u.acheteur', 'a')
            ->innerJoin('u.achats', 'v')
            ->andWhere('u.etat = :etat')
            ->andWhere('u.type = :type')
            ->andWhere('u.datecreation >= :du')
            ->andWhere('u.datecreation <= :au')
            ->andWhere('a.nom LIKE :value OR a.prenom LIKE :value OR a.nif LIKE :value OR a.nrc LIKE :value OR u.nf LIKE :value OR v.name LIKE :value OR v.totalHT LIKE :value OR v.totalTTC LIKE :value')
            ->andWhere('z.id = :zone')

            ->andWhere('u.user = :user')
            ->setParameter('etat', $etat)
            ->setParameter('type', $type)
            ->setParameter('du', $du)
            ->setParameter('au', $au)
            ->setParameter('zone', $zone)
            ->setParameter('value', '%'.$mot.'%')
            ->setParameter('user', $user);
        ;
        return $qb->getQuery()->getResult();
    }
    public function search2($etat,$type,$du,$au,$mot,$user)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->innerJoin('u.acheteur', 'a')
            ->innerJoin('u.achats', 'v')
            ->andWhere('u.etat = :etat')
            ->andWhere('u.type = :type')
            ->andWhere('u.datecreation >= :du')
            ->andWhere('u.datecreation <= :au')
            ->andWhere('a.nom LIKE :value OR a.prenom LIKE :value OR a.nif LIKE :value OR a.nrc LIKE :value OR u.nf LIKE :value OR v.name LIKE :value OR v.totalHT LIKE :value OR v.totalTTC LIKE :value')
            ->andWhere('u.user = :user')


            ->setParameter('etat', $etat)
            ->setParameter('type', $type)
            ->setParameter('du', $du)
            ->setParameter('au', $au)
            ->setParameter('value', '%'.$mot.'%')
            ->setParameter('user', $user);
        ;
        return $qb->getQuery()->getResult();
    }
    public function delete($bon)
    {
        $qb = $this->createQueryBuilder('u')
            ->delete('u')
            ->where('u.id = :id')

            ->setParameter('id', $bon)


        ;
        return $qb->getQuery()->getResult();
    }
    public function graphesTTC($typeRapport,$du,$au,$grouperPar,$zone,$additionnelle,$montants,$type,$etat,$contact,$user)
    {

        $config = $this->getEntityManager()->getConfiguration();


        $qb = $this->createQueryBuilder('u')
            ->Select('u.datecreation, 
            YEAR(u.datecreation) as year, 
            QUARTER(u.datecreation) as quarter, 
             MONTH(u.datecreation) as month,
              WEEK(u.datecreation) as week,
               DAY(u.datecreation) as day,
            SUM(v.totalTTCa) as total')
            ->leftJoin('u.achats', 'v')


            ->andWhere('u.etat = :etat')
            ->andWhere('u.user = :user')
            ->groupBy($grouperPar)


            ->setParameter('etat', $etat)
            ->setParameter('user', $user)

        ;

        return $qb->getQuery()->getResult();
    }
    public function graphesHT($typeRapport,$du,$au,$grouperPar,$zone,$additionnelle,$montants,$type,$etat,$contact,$user)
    {

        $qb = $this->createQueryBuilder('u')
            ->Select('u.datecreation, 
            YEAR(u.datecreation) as year, 
            QUARTER(u.datecreation) as quarter, 
             MONTH(u.datecreation) as month,
              WEEK(u.datecreation) as week,
               DAY(u.datecreation) as day,
            SUM(v.totalHTa) as total')
            ->leftJoin('u.achats', 'v')



            ->andWhere('u.etat = :etat')
            ->andWhere('u.user = :user')



            ->setParameter('etat', $etat)
            ->setParameter('user', $user)

        ;

        return $qb->getQuery()->getResult();
    }

}
