<?php

namespace Commandes\CommandesBundle\Repository;

/**
 * TablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamettresRepository extends \Doctrine\ORM\EntityRepository
{


}
