<?php

namespace Commandes\CommandesBundle\Repository;

/**
 * SectiondocsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamgestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($user)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.user = :user')

            ->setParameter('user', $user)
        ;

        return $qb->getQuery()->getResult();
    }
}
