<?php

namespace Commandes\CommandesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ProduitsRepository extends EntityRepository
{
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.id IN (:array)')
            ->andWhere('u.aff = 1 ')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
    public function search($mot,$zone)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->where('u.name LIKE :value')
            ->andWhere('u.aff = 1 ')



            ->setParameter('value', '%'.$mot.'%')



        ;
        return $qb->getQuery()->getResult();
    }

    public function search2($mot,$user)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->where('u.name LIKE :value')
            ->andWhere('u.aff = 1 ')
            ->andWhere('u.user = :user ')

            ->setParameter('value', '%'.$mot.'%')
            ->setParameter('user', $user)

        ;
        return $qb->getQuery()->getResult();
    }

    public function delete($id)
    {
        $qb = $this->createQueryBuilder('u')
            ->update()
            ->set('u.aff', '?1')
            ->where('u.id = :id')


            ->setParameter('1', 0)
            ->setParameter('id', $id)


        ;
        return $qb->getQuery()->getResult();
    }

    public function Name($nom)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->where('u.name LIKE :value')
            ->andWhere('u.aff = 1 ')

            ->setParameter('value', '%'.$nom.'%')



        ;
        return $qb->getQuery()->getArrayResult();
    }
}
