<?php

namespace Commandes\CommandesBundle\Repository;

/**
 * SuiviFactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviFactsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByfacture($facture)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.factures = :facture')

            ->orderBy('u.id', 'DESC')
            ->setParameter('facture', $facture)
            ;

        return $qb->getQuery()->getResult();
    }

    public function findByProforma($proforma)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.proformas = :proforma')

            ->orderBy('u.id', 'DESC')
            ->setParameter('proforma', $proforma)
        ;

        return $qb->getQuery()->getResult();
    }
    public function findByRecu($recus)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.recus = :recu')

            ->orderBy('u.id', 'DESC')
            ->setParameter('recu', $recus)
        ;

        return $qb->getQuery()->getResult();
    }
    public function findByDevi($devi)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.devis = :devi')

            ->orderBy('u.id', 'DESC')
            ->setParameter('devi', $devi)
        ;

        return $qb->getQuery()->getResult();
    }
    public function findBybdc($bonscommande)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.bonscommandes = :bdc')

            ->orderBy('u.id', 'DESC')
            ->setParameter('bdc', $bonscommande)
        ;

        return $qb->getQuery()->getResult();
    }
    public function findByDepenses($depense)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.depenses = :depenses')

            ->orderBy('u.id', 'DESC')
            ->setParameter('depenses', $depense)
        ;

        return $qb->getQuery()->getResult();
    }
}
