imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }


# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    brochures_directory: '%kernel.root_dir%/../web/imgProduit'

framework:
    translator: { fallbacks: [fr] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        dql:
           datetime_functions:
              DAY: DoctrineExtensions\Query\Mysql\Day
              MONTH: DoctrineExtensions\Query\Mysql\Month
              YEAR: DoctrineExtensions\Query\Mysql\Year
              WEEK: DoctrineExtensions\Query\Mysql\Week
              WEEKDAY: DoctrineExtensions\Query\Mysql\WeekDay
              YEARMONTH: DoctrineExtensions\Query\Mysql\YearMonth
              YEARWEEK: DoctrineExtensions\Query\Mysql\YearWeek
           numeric_functions:
              QUARTER: DoctrineExtensions\Query\Mysql\Quarter
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }



ivory_ck_editor:
    configs:
        my_config_1:
            toolbar: "my_toolbar_1"

            # ...
        my_config_2:
            toolbar: "my_toolbar_2"
            uiColor: "#ffffff"
            # ...
        my_config_2:
            toolbar: "my_toolbar_1"
            uiColor: "#cccccc"
    toolbars:
        configs:
            my_toolbar_1: [ [ "Bold", "-", "Italic","Underline","NumberedList","BulletedList","JustifyLeft","JustifyCenter","JustifyRight" ],  [ 'Styles', 'Format','Font','FontSize' ] ,[ "TextColor", "BGColor" ] ]
            my_toolbar_2: [ [ "Source" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]





avalanche_imagine:
    source_root:  %kernel.root_dir%/../web/imgProduit
    web_root:     %kernel.root_dir%/../web/
    cache_prefix: media/cache
    driver:       gd
    filters:

        banniere:
            type:    thumbnail
            options: { size: [1050, 350], mode: outbound, quality: 100, format: png}

        produit:
            type:    thumbnail
            options: { size: [135, 135], mode: outbound, quality: 100, format: jpeg}

        choix:
            type:    thumbnail
            options: { size: [270, 207], mode: outbound, quality: 100, format: png}
        show:
            type:    thumbnail
            options: { size: [700, 700], mode: outbound, quality: 100, format: png}

        detaillemini:
            type:    thumbnail
            options: { size: [174, 215], mode: outbound, quality: 100, format: png}

        partenaire:
            type:    thumbnail
            options: { size: [124, 154], mode: outbound, quality: 100, format: png}

        evidence:
            type:    thumbnail
            options: { size: [387, 480], mode: outbound, quality: 100, format: png}

        partenaire:
            type:    thumbnail
            options: { size: [188, 139], mode: outbound, quality: 100, format: png}

fos_user:
    registration:
        form:
            name: app_user_registration
        confirmation:
            enabled: false

    profile:
        form:
            type: Commandes\CommandesBundle\Form\ProfileFormType

    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Commandes\CommandesBundle\Entity\User
    from_email:
                  address: 	contact@creativ-dz.com
                  sender_name: Creativ Web

genemu_form:
    select2:
        enabled: true
        configs:
            placeholder: Select a value
            width: 100%
            allowClear: false
            minimumInputLength: 0


twig:
    form_themes:
        - ':Form:fields.html.twig'

    number_format:
          decimals: 2
          decimal_point: ','
          thousands_separator: '.'

    form:
        resources:
            - 'TetranzSelect2EntityBundle:Form:fields.html.twig'

