commandes:
    resource: "@CommandesBundle/Resources/config/routing.yml"
    prefix:   /



utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"



_imagine:
    resource: .
    type:     imagine