services:
#    commandes.example:
#        class: Commandes\CommandesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    setNewReference:
      class: Commandes\CommandesBundle\Services\GetReference
      arguments: [@security.context, @doctrine.orm.entity_manager]

    setNewFacture:
      class: Commandes\CommandesBundle\Services\GetFacture
      arguments: [@service_container, @doctrine.orm.entity_manager]

    form.type.datalist_type:
        class: Commandes\CommandesBundle\Form\DatalistType
        tags:
            -  { name: form.type, alias: datalist }



