admin_commandescafe_index:
    path:     /
    defaults: { _controller: "CommandesBundle:Commandescafes:index" }
    methods:  GET

admin_commandescafe_show:
    path:     /{id}/show
    defaults: { _controller: "CommandesBundle:Commandescafes:show" }
    methods:  GET

admin_commandescafe_new:
    path:     /new
    defaults: { _controller: "CommandesBundle:Commandescafes:new" }
    methods:  [GET, POST]

admin_commandescafe_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommandesBundle:Commandescafes:edit" }
    methods:  [GET, POST]

admin_commandescafe_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommandesBundle:Commandescafes:delete" }
    methods:  DELETE
