admin_configs_index:
    path:     /
    defaults: { _controller: "CommandesBundle:Configs:index" }
    methods:  GET

admin_configs_show:
    path:     /{id}/show
    defaults: { _controller: "CommandesBundle:Configs:show" }
    methods:  GET

admin_configs_new:
    path:     /new
    defaults: { _controller: "CommandesBundle:Configs:new" }
    methods:  [GET, POST]

admin_configs_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommandesBundle:Configs:edit" }
    methods:  [GET, POST]

admin_configs_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommandesBundle:Configs:delete" }
    methods:  DELETE
