admin_familles_index:
    path:     /
    defaults: { _controller: "CommandesBundle:Familles:index" }
    methods:  GET

admin_familles_show:
    path:     /{id}/show
    defaults: { _controller: "CommandesBundle:Familles:show" }
    methods:  GET

admin_familles_new:
    path:     /new
    defaults: { _controller: "CommandesBundle:Familles:new" }
    methods:  [GET, POST]

admin_familles_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommandesBundle:Familles:edit" }
    methods:  [GET, POST]

admin_familles_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommandesBundle:Familles:delete" }
    methods:  DELETE
