admin_parametres_index:
    path:     /
    defaults: { _controller: "CommandesBundle:Paramettres:index" }
    methods:  GET

admin_parametres_show:
    path:     /{id}/show
    defaults: { _controller: "CommandesBundle:Paramettres:show" }
    methods:  GET

admin_parametres_new:
    path:     /new
    defaults: { _controller: "CommandesBundle:Paramettres:new" }
    methods:  [GET, POST]

admin_parametres_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommandesBundle:Paramettres:edit" }
    methods:  [GET, POST]

admin_parametres_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommandesBundle:Paramettres:delete" }
    methods:  DELETE
